account_types:

user_types:
  guest:
    can:
      read:
        - Project

roles:
  guest:
    can:
      read:
        - all

role_groups:

licenses:
  bloggers:
    can:
      manage:
        - Post

users:
